services:
  bankbapi:
    image: myregistry/banka-api:latest
    container_name: banka-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5002:8080"
    depends_on:
      - kafka
